INSERT INTO register.properties(address) VALUES
    ('153, Castle Road, Pontypandy'),
    ('154, Pleasant Road, Pontypandy'),
    ('15, Castle Street, Pontypandy'),
    ('105, Owain Road, Pontypandy'),
    ('8, Castle Bank, Pontypandy'),
    ('58, Mountain Road, Pontypandy'),
    ('180, Castle Road, Pontypandy'),
    ('98, Mountain Road, Pontypandy'),
    ('43, Marketstreet, Pontypandy'),
    ('137, Castle Bank, Pontypandy'),
    ('18, Glyndŵr Street, Pontypandy'),
    ('168, Castle Street, Pontypandy'),
    ('24, Bank Road, Pontypandy'),
    ('145, Owain Court, Pontypandy'),
    ('156, Mountain Drive, Pontypandy'),
    ('83, Idwal Street, Pontypandy'),
    ('86, Castle Bank, Pontypandy'),
    ('132, Glyndŵr Drive, Pontypandy'),
    ('65, Pleasant Road, Pontypandy'),
    ('115, Mountain Court, Pontypandy'),
    ('35, Owain Road, Pontypandy'),
    ('140, Owain Road, Pontypandy'),
    ('26, Glyndŵr Drive, Pontypandy'),
    ('191, Mountain Court, Pontypandy'),
    ('8, Mountain Road, Pontypandy'),
    ('101, Pleasant Road, Pontypandy'),
    ('196, Castle Street, Pontypandy'),
    ('65, Castle Street, Pontypandy'),
    ('103, Glyndŵr Drive, Pontypandy'),
    ('10, Gooodview Court, Pontypandy'),
    ('57, Castle Street, Pontypandy'),
    ('141, Pleasant Road, Pontypandy'),
    ('20, Castle Street, Pontypandy'),
    ('144, Marketstreet, Pontypandy'),
    ('199, Bank Road, Pontypandy'),
    ('11, Bank Road, Pontypandy'),
    ('78, Pleasant Road, Pontypandy'),
    ('50, Bank Street, Pontypandy'),
    ('189, Bank Road, Pontypandy'),
    ('199, Highstreet, Pontypandy'),
    ('132, Castle Bank, Pontypandy'),
    ('124, Pleasant Road, Pontypandy'),
    ('110, Glyndŵr Road, Pontypandy'),
    ('136, Pleasant Road, Pontypandy'),
    ('159, Idwal Street, Upper Leadworth'),
    ('177, Owain Road, Upper Leadworth'),
    ('152, Castle Street, Upper Leadworth'),
    ('15, Mountain Drive, Upper Leadworth'),
    ('174, Mountain Road, Upper Leadworth'),
    ('38, Highstreet, Upper Leadworth'),
    ('133, Pleasant Drive, Upper Leadworth'),
    ('141, Mountain Drive, Upper Leadworth'),
    ('90, Idwal Court, Upper Leadworth'),
    ('32, Idwal Court, Upper Leadworth'),
    ('178, Pleasant Road, Upper Leadworth'),
    ('199, Mountain Court, Upper Leadworth'),
    ('194, Highstreet, Upper Leadworth'),
    ('100, Owain Court, Upper Leadworth'),
    ('190, Glyndŵr Street, Upper Leadworth'),
    ('114, Glyndŵr Bank, Upper Leadworth'),
    ('107, Glyndŵr Bank, Upper Leadworth'),
    ('65, Glyndŵr Drive, Upper Leadworth'),
    ('169, Bank Street, Upper Leadworth'),
    ('122, Mountain Drive, Upper Leadworth'),
    ('22, Bank Street, Upper Leadworth'),
    ('27, Castle Road, Upper Leadworth'),
    ('86, Pleasant Street, Upper Leadworth'),
    ('178, Owain Court, Upper Leadworth'),
    ('111, Pleasant Drive, Upper Leadworth'),
    ('64, Mountain Court, Upper Leadworth'),
    ('123, Castle Street, Upper Leadworth'),
    ('170, Mountain Road, Upper Leadworth'),
    ('120, Pleasant Street, Upper Leadworth'),
    ('164, Pleasant Drive, Upper Leadworth'),
    ('94, Glyndŵr Drive, Upper Leadworth'),
    ('189, Glyndŵr Bank, Upper Leadworth'),
    ('28, Castle Road, Upper Leadworth'),
    ('73, Goodview Street, Upper Leadworth'),
    ('153, Bank Road, Upper Leadworth'),
    ('171, Glyndŵr Road, Upper Leadworth'),
    ('35, Gooodview Court, Upper Leadworth'),
    ('20, Highstreet, Upper Leadworth'),
    ('43, Idwal Court, Upper Leadworth'),
    ('139, Idwal Court, Upper Leadworth'),
    ('25, Pleasant Street, Upper Leadworth'),
    ('75, Marketstreet, Upper Leadworth'),
    ('95, Bank Road, Upper Leadworth'),
    ('114, Castle Road, Upper Leadworth'),
    ('163, Mountain Road, Upper Leadworth'),
    ('112, Owain Court, Upper Leadworth'),
    ('162, Glyndŵr Street, Upper Leadworth'),
    ('65, Glyndŵr Street, Upper Leadworth'),
    ('156, Idwal Court, Upper Leadworth'),
    ('58, Pleasant Road, Upper Leadworth'),
    ('108, Bank Road, Upper Leadworth'),
    ('126, Glyndŵr Drive, Upper Leadworth'),
    ('10, Owain Court, Upper Leadworth'),
    ('47, Pleasant Road, Upper Leadworth'),
    ('35, Owain Road, Upper Leadworth'),
    ('84, Glyndŵr Bank, Upper Leadworth'),
    ('169, Pleasant Drive, Upper Leadworth'),
    ('199, Mountain Road, Upper Leadworth'),
    ('61, Marketstreet, Upper Leadworth'),
    ('199, Bank Road, Upper Leadworth'),
    ('97, Glyndŵr Bank, Upper Leadworth'),
    ('74, Mountain Court, Upper Leadworth'),
    ('26, Mountain Road, Upper Leadworth'),
    ('175, Glyndŵr Street, Upper Leadworth'),
    ('89, Glyndŵr Road, Upper Leadworth'),
    ('96, Glyndŵr Road, Upper Leadworth'),
    ('174, Marketstreet, Upper Leadworth'),
    ('180, Glyndŵr Street, Upper Leadworth'),
    ('152, Pleasant Drive, Upper Leadworth'),
    ('31, Idwal Street, Upper Leadworth'),
    ('19, Mountain Road, Upper Leadworth'),
    ('32, Pleasant Street, Upper Leadworth'),
    ('171, Marketstreet, Upper Leadworth'),
    ('149, Owain Court, Upper Leadworth'),
    ('44, Pleasant Drive, Upper Leadworth'),
    ('84, Mountain Court, Upper Leadworth'),
    ('187, Pleasant Street, Upper Leadworth'),
    ('124, Mountain Drive, Upper Leadworth'),
    ('158, Goodview Street, Upper Leadworth'),
    ('16, Bank Road, Upper Leadworth'),
    ('147, Highstreet, Upper Leadworth'),
    ('172, Castle Street, Upper Leadworth'),
    ('62, Pleasant Street, Upper Leadworth'),
    ('71, Owain Road, Upper Leadworth'),
    ('18, Glyndŵr Bank, Upper Leadworth'),
    ('64, Pleasant Road, Upper Leadworth'),
    ('177, Goodview Street, Upper Leadworth'),
    ('12, Mountain Road, Upper Leadworth'),
    ('105, Mountain Road, Upper Leadworth'),
    ('129, Glyndŵr Street, Upper Leadworth'),
    ('33, Idwal Street, Upper Leadworth'),
    ('113, Owain Court, Upper Leadworth'),
    ('114, Castle Bank, Upper Leadworth'),
    ('162, Bank Street, Upper Leadworth'),
    ('105, Bank Road, Upper Leadworth'),
    ('199, Idwal Street, Upper Leadworth'),
    ('128, Highstreet, Upper Leadworth'),
    ('164, Gooodview Court, Upper Leadworth'),
    ('101, Castle Road, Upper Leadworth'),
    ('181, Mountain Road, Upper Leadworth'),
    ('12, Bank Street, Upper Leadworth'),
    ('92, Castle Road, Upper Leadworth'),
    ('34, Glyndŵr Drive, Upper Leadworth'),
    ('112, Mountain Court, Upper Leadworth'),
    ('72, Pleasant Drive, Upper Leadworth'),
    ('92, Glyndŵr Bank, Upper Leadworth'),
    ('75, Pleasant Street, Upper Leadworth'),
    ('64, Pleasant Street, Upper Leadworth'),
    ('52, Marketstreet, Upper Leadworth'),
    ('37, Owain Court, Upper Leadworth'),
    ('2, Castle Street, Upper Leadworth'),
    ('160, Idwal Street, Upper Leadworth'),
    ('80, Castle Bank, Upper Leadworth'),
    ('36, Idwal Court, Upper Leadworth'),
    ('131, Castle Road, Upper Leadworth'),
    ('131, Pleasant Road, Upper Leadworth'),
    ('182, Glyndŵr Drive, Upper Leadworth'),
    ('58, Idwal Court, Upper Leadworth'),
    ('158, Bank Road, Upper Leadworth'),
    ('190, Glyndŵr Drive, Upper Leadworth'),
    ('17, Marketstreet, Upper Leadworth'),
    ('6, Bank Road, Upper Leadworth'),
    ('107, Highstreet, Upper Leadworth'),
    ('93, Mountain Court, Upper Leadworth'),
    ('76, Pleasant Street, Upper Leadworth'),
    ('115, Mountain Drive, Upper Leadworth'),
    ('114, Bank Street, Upper Leadworth'),
    ('187, Castle Bank, Upper Leadworth'),
    ('92, Goodview Street, Upper Leadworth'),
    ('120, Castle Bank, Upper Leadworth'),
    ('121, Castle Bank, Upper Leadworth'),
    ('68, Pleasant Street, Upper Leadworth'),
    ('24, Owain Court, Upper Leadworth'),
    ('38, Marketstreet, Upper Leadworth'),
    ('82, Goodview Street, Upper Leadworth'),
    ('110, Highstreet, Upper Leadworth'),
    ('61, Pleasant Road, Upper Leadworth'),
    ('170, Owain Court, Upper Leadworth'),
    ('104, Mountain Drive, Upper Leadworth'),
    ('109, Castle Bank, Upper Leadworth'),
    ('52, Goodview Street, Upper Leadworth'),
    ('68, Mountain Road, Upper Leadworth'),
    ('154, Glyndŵr Street, Upper Leadworth'),
    ('108, Castle Street, Upper Leadworth'),
    ('141, Owain Court, Upper Leadworth'),
    ('153, Owain Court, Upper Leadworth'),
    ('140, Mountain Drive, Upper Leadworth'),
    ('68, Highstreet, Upper Leadworth'),
    ('197, Highstreet, Upper Leadworth'),
    ('189, Glyndŵr Road, Upper Leadworth'),
    ('181, Glyndŵr Bank, Upper Leadworth'),
    ('193, Bank Street, Upper Leadworth'),
    ('98, Glyndŵr Road, Upper Leadworth'),
    ('121, Goodview Street, Upper Leadworth'),
    ('88, Idwal Street, Upper Leadworth'),
    ('176, Castle Road, Upper Leadworth'),
    ('106, Owain Road, Upper Leadworth'),
    ('49, Bank Street, Upper Leadworth'),
    ('139, Marketstreet, Upper Leadworth'),
    ('34, Mountain Road, Upper Leadworth'),
    ('142, Idwal Street, Upper Leadworth'),
    ('164, Owain Road, Upper Leadworth'),
    ('65, Pleasant Road, Upper Leadworth'),
    ('199, Gooodview Court, Upper Leadworth'),
    ('125, Goodview Street, Upper Leadworth'),
    ('135, Owain Court, Upper Leadworth'),
    ('108, Mountain Court, Upper Leadworth'),
    ('115, Castle Road, Upper Leadworth'),
    ('132, Goodview Street, Upper Leadworth'),
    ('93, Mountain Drive, Upper Leadworth'),
    ('82, Mountain Court, Upper Leadworth'),
    ('46, Castle Street, Upper Leadworth'),
    ('187, Pleasant Road, Upper Leadworth'),
    ('123, Mountain Court, Upper Leadworth'),
    ('116, Pleasant Street, Upper Leadworth'),
    ('67, Idwal Street, Upper Leadworth'),
    ('136, Mountain Court, Upper Leadworth'),
    ('134, Glyndŵr Road, Upper Leadworth'),
    ('94, Highstreet, Upper Leadworth'),
    ('109, Pleasant Road, Upper Leadworth'),
    ('21, Glyndŵr Drive, Upper Leadworth'),
    ('131, Highstreet, Upper Leadworth'),
    ('60, Pleasant Road, Upper Leadworth'),
    ('18, Pleasant Street, Upper Leadworth'),
    ('47, Mountain Road, Upper Leadworth'),
    ('182, Glyndŵr Road, Upper Leadworth'),
    ('30, Idwal Street, Upper Leadworth'),
    ('181, Bank Road, Upper Leadworth'),
    ('171, Castle Road, Upper Leadworth'),
    ('115, Owain Court, Upper Leadworth'),
    ('60, Owain Court, Upper Leadworth'),
    ('93, Glyndŵr Bank, Upper Leadworth'),
    ('90, Pleasant Street, Upper Leadworth'),
    ('137, Marketstreet, Upper Leadworth'),
    ('36, Castle Bank, Upper Leadworth'),
    ('43, Owain Court, Upper Leadworth'),
    ('156, Castle Road, Upper Leadworth'),
    ('197, Idwal Court, Upper Leadworth'),
    ('172, Mountain Court, Upper Leadworth'),
    ('35, Glyndŵr Drive, Upper Leadworth'),
    ('58, Mountain Drive, Upper Leadworth'),
    ('183, Castle Bank, Upper Leadworth'),
    ('156, Marketstreet, Upper Leadworth'),
    ('178, Marketstreet, Upper Leadworth'),
    ('38, Goodview Street, Upper Leadworth'),
    ('184, Mountain Road, Upper Leadworth'),
    ('89, Bank Street, Upper Leadworth'),
    ('91, Highstreet, Upper Leadworth'),
    ('135, Pleasant Drive, Upper Leadworth'),
    ('159, Gooodview Court, Upper Leadworth'),
    ('59, Idwal Street, Upper Leadworth'),
    ('107, Mountain Court, Upper Leadworth'),
    ('28, Pleasant Road, Upper Leadworth'),
    ('55, Goodview Street, Upper Leadworth'),
    ('104, Owain Road, Upper Leadworth'),
    ('45, Castle Road, Upper Leadworth'),
    ('24, Marketstreet, Upper Leadworth'),
    ('66, Owain Court, Upper Leadworth'),
    ('138, Marketstreet, Upper Leadworth'),
    ('3, Castle Street, Upper Leadworth'),
    ('111, Marketstreet, Upper Leadworth'),
    ('133, Pleasant Street, Upper Leadworth'),
    ('111, Castle Street, Upper Leadworth'),
    ('145, Bank Street, Upper Leadworth'),
    ('187, Glyndŵr Drive, Upper Leadworth'),
    ('26, Idwal Court, Upper Leadworth'),
    ('186, Pleasant Street, Upper Leadworth'),
    ('75, Bank Street, Upper Leadworth'),
    ('173, Pleasant Drive, Upper Leadworth'),
    ('53, Bank Road, Upper Leadworth'),
    ('64, Idwal Street, Upper Leadworth'),
    ('169, Pleasant Street, Upper Leadworth'),
    ('50, Idwal Court, Upper Leadworth'),
    ('126, Bank Street, Upper Leadworth'),
    ('102, Goodview Street, Upper Leadworth'),
    ('62, Gooodview Court, Upper Leadworth'),
    ('64, Castle Bank, Cwmderi'),
    ('170, Bank Street, Cwmderi'),
    ('168, Mountain Drive, Cwmderi'),
    ('49, Mountain Court, Cwmderi'),
    ('88, Mountain Court, Cwmderi'),
    ('72, Castle Bank, Cwmderi'),
    ('140, Glyndŵr Street, Cwmderi'),
    ('164, Owain Road, Cwmderi'),
    ('148, Mountain Drive, Cwmderi'),
    ('135, Mountain Road, Cwmderi'),
    ('45, Mountain Court, Cwmderi'),
    ('11, Gooodview Court, Cwmderi'),
    ('34, Pleasant Drive, Cwmderi'),
    ('170, Bank Road, Cwmderi'),
    ('176, Idwal Street, Cwmderi'),
    ('22, Glyndŵr Street, Cwmderi'),
    ('164, Glyndŵr Bank, Cwmderi'),
    ('99, Bank Street, Cwmderi'),
    ('63, Mountain Drive, Cwmderi'),
    ('182, Glyndŵr Street, Cwmderi'),
    ('81, Owain Road, Cwmderi'),
    ('11, Marketstreet, Cwmderi'),
    ('190, Highstreet, Cwmderi'),
    ('73, Glyndŵr Bank, Cwmderi'),
    ('1, Highstreet, Cwmderi'),
    ('88, Gooodview Court, Cwmderi'),
    ('81, Pleasant Street, Cwmderi'),
    ('23, Castle Road, Cwmderi'),
    ('73, Glyndŵr Road, Cwmderi'),
    ('199, Glyndŵr Road, Cwmderi'),
    ('14, Bank Street, Cwmderi'),
    ('149, Gooodview Court, Cwmderi'),
    ('27, Bank Road, Cwmderi'),
    ('14, Glyndŵr Drive, Cwmderi'),
    ('43, Bank Road, Cwmderi'),
    ('87, Pleasant Road, Cwmderi'),
    ('105, Gooodview Court, Cwmderi'),
    ('52, Highstreet, Cwmderi'),
    ('83, Highstreet, Cwmderi'),
    ('78, Owain Court, Cwmderi'),
    ('19, Mountain Road, Cwmderi'),
    ('143, Idwal Court, Cwmderi'),
    ('194, Highstreet, Cwmderi'),
    ('72, Marketstreet, Cwmderi'),
    ('148, Owain Court, Cwmderi'),
    ('195, Owain Court, Cwmderi'),
    ('139, Idwal Street, Cwmderi'),
    ('107, Gooodview Court, Cwmderi'),
    ('154, Pleasant Street, Cwmderi'),
    ('78, Marketstreet, Cwmderi'),
    ('90, Castle Road, Cwmderi'),
    ('181, Castle Street, Cwmderi'),
    ('193, Owain Court, Cwmderi'),
    ('41, Marketstreet, Cwmderi'),
    ('82, Pleasant Road, Cwmderi'),
    ('162, Mountain Drive, Cwmderi'),
    ('180, Goodview Street, Cwmderi'),
    ('133, Glyndŵr Road, Cwmderi'),
    ('31, Castle Bank, Cwmderi'),
    ('175, Glyndŵr Bank, Cwmderi'),
    ('164, Mountain Court, Cwmderi');

INSERT INTO register.attribute_types(attribute_type, description) VALUES
    ('second_home', 'The property is recognised as a second home'),
    ('buy_to_let', 'The property is recognised as a buy to let property'),
    ('attribute_a', 'Example of a multiplyer attribute'),
    ('attribute_b', 'Example of a fixed amount add attribute');
